language: python
python:
    - "2.7"
    - "3.7"
    - "pypy"
    - "pypy3"

cache:
  pip: true
  directories:
  - google-cloud-sdk
  - redis-git

install:
    - pip install -U setuptools
    - pip install -r requirements/ci.txt

services:
    - redis-server
    - memcached

before_script:
    - make -f Makefile.tests tests

script: nosetests tests --with-cov -v
after_success:
    - coveralls
