language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy-5.3"

cache:
  pip: true
  directories:
  - google-cloud-sdk
  - redis-git

install:
    - pip install -r requirements/ci.txt

services:
    - redis-server
    - memcached

before_script:
    - make -f Makefile.tests tests

script: nosetests tests --with-cov -v
after_success:
    - coveralls
