language: python
python:
    - "2.7"
    - "3.7"
    - "3.8"
    - "pypy"
    - "pypy3"

cache:
  pip: true
  directories:
  - google-cloud-sdk
  - redis-git

install:
    - pip install -U setuptools
    - pip install -r requirements/ci.txt

services:
    - redis-server
    - memcached

script: make -f Makefile.tests tests
after_success:
    - coveralls
